
	<meta charset="utf-8">

	<!-- Favicons für unterschiedliche Systeme (von realfavicongenerator.net) -->
	<link rel="apple-touch-icon" sizes="180x180" href="<?php echo _URL_;?>favicons/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="<?php echo _URL_;?>favicons/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="<?php echo _URL_;?>favicons/favicon-16x16.png">
	<link rel="icon" sizes="192x192" href="<?php echo _URL_;?>favicons/android-chrome-192x192.png">
	<link rel="manifest" href="<?php echo _URL_;?>manifest.json">
	<link rel="mask-icon" href="<?php echo _URL_;?>favicons/safari-pinned-tab.svg" color="#5bbad5">
	<link rel="shortcut icon" href="<?php echo _URL_;?>favicons/favicon.ico">
	<meta name="apple-mobile-web-app-title" content="GWN-Liste">
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="application-name" content="GWN-Liste">
	<meta name="msapplication-TileColor" content="#da532c">
	<meta name="msapplication-config" content="<?php echo _URL_;?>favicons/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">

	<!-- Andere Metadaten -->
	<meta name="description" content="Adressverzeichnis f&uuml;r Vereinsmitglieder des <?php echo $config["Base"]["VereinLong"];?>">
	<meta name="keywords" content="Adressliste, Adressverzeichnis, <?php echo $config["Base"]["VereinShort"];?>, <?php echo $config["Base"]["Verein"];?>, <?php echo $config["Base"]["VereinLong"];?>, Mitglieder, Trainer, Betreuer">
	<meta name="author" content="Nils Uhde">
	<meta name="copyright" content="Nils Uhde, <?php echo $config["Base"]["VereinLong"];?>">
	<meta name="robots" content="noindex, nofollow">
	<meta http-equiv="cache-control" content="no-cache">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>GWN &middot; Adressenliste</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css" integrity="sha384-v2Tw72dyUXeU3y4aM2Y0tBJQkGfplr39mxZqlTBDUZAb9BGoC40+rdFCG0m10lXk" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/fontawesome.css" integrity="sha384-q3jl8XQu1OpdLgGFvNRnPdj5VIlCvgsDQTQB6owSOHWlAurxul7f+JpUOVdAiJ5P" crossorigin="anonymous">
	<link href="<?php echo _URL_;?>css/gwn.css" rel="stylesheet" type="text/css">

